# Generated by Django 5.0 on 2023-12-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlashCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("front_image", models.ImageField(upload_to="flashcards/")),
                ("front_definition", models.CharField(max_length=255)),
                ("back_image", models.ImageField(upload_to="flashcards/")),
                ("back_word", models.CharField(max_length=255)),
            ],
        ),
    ]
