# Generated by Django 5.0 on 2024-01-12 04:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0006_card_set_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card_set",
            name="user",
        ),
    ]
